### ISSUE TITLE
Just figured i would mention this.

### ISSUE THREAD

**Issue by Growlith1223** [ratty27/ArsMagica2-rt#1]
I like that people are helping but I had decided months ago to rewrite the entire mod from the ground up, You're free to do whatever, by all means, but don't expect me to use this.

**Comment by ratty27** [comment]
Thank you for notice. And If you feel uncomfortable, I'm sorry.

When I found your repository on github, I thought it is stopped. Because no commits in long time, and many pull requests are stayed. And I began maintenance as unofficial version, it is mainly for play myself.
After worked, I knew that you are working on forum of other site. I changed plan to prepare patches of fixed bugs for when you complete the update.
Then, Today, I decided to delete my work. I knew this is waste, because you are rewriting.
Please close this issue, when you read this message. I will delete this repository.

I am a fan of ArsMagica2 too. Good luck!

**Comment by Growlith1223** [comment]
yea, sorry to burst your bubble there.
